# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaMjGLd0gjgw-kbuNXsBNZ_iERdXaL8_
"""

print("Cuál es el peso del padre en kg: ")
	padre = int(input())
	madre = int(2*padre+4)
	hijo = int((madre+padre)/5)
	print(padre, madre, hijo)
	if hijo>=0 and hijo<=20:
		print("uno")
	else:
		if hijo>=21 and hijo<=40:
			print("dos")
		else:
			if hijo>=41 and hijo<=80:
				print("tres")
			else:
				if hijo>80:
					print("cuatro")