# -*- coding: utf-8 -*-
"""20220418.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNMNUp_CCSEE1fmjkqJXzVpK23R4GtcT
"""

print("Hola, Mundo!")

print("Christian Bermúdez Rivas")

# Así se hacen comentarios
print(type(10))
print(type(3.14))
print(type(-8))
print(type(1e3))

print(type("i_am_an_integer"))
print(type(3.54))
print(type(7 // 8))
print(type( 1))
print(type("hola" + "adiós"))
print(type( 4e4))
print(type(12 / 3))

print("a)",type("i_am_an_integer"))
print("b)",type(3.54))
print("c)",type(7 // 8))
print("d)",type( 1))
print("e)",type("hola" + "adiós"))
print("f)",type( 4e4))
print("g)",type(12 / 3))

3*2+1

print("a)",type("i_am_an_integer"))