# -*- coding: utf-8 -*-
"""20220503.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpte9hQV_m2DOnEohEPEKIC4_lNoEVQG

# Listas
"""

list1 = [1,2,3,4,5,6,7,8,9,10]
print(list1)

nombres=["Juan", "Pedro", "Maria", "Duverli", "Bryan", "Esniver", "Usnavy", "Dualinquer"]
print(nombres)
print(nombres[0])

#CARLOS MAURICIO SUAREZ LOPEZ
lista1 = ["angela", "patricia", "isabella","carlos"]
print(lista1)

# Carolina Tovar cerón
list_nombres={"carolina" ,"daniela" ,"claudia" ,"fernando" ,"isabel" ,"antonia" ,"fernanda" ,"cristobal"}
print(list_nombres)

#Cesar augusto Tique arbelaez

list1=["juan","pedro","cesar","augusto"]
print(list1)

"""## Función **len()**"""

list1=["juan","pedro","cesar","augusto"]
len(list1)

"""## Concatenar listas

Se concatenan las listas usando el símbolo +
"""

nombres=["Juan", "Pedro", "Maria", "Duverli", "Bryan", "Esniver", "Usnavy", "Dualinquer"]
apellidos=["Birbiquí", "Sampues", "Chuchimí", "Caderín", "Pasto", "Pernir", "Adujú", "Bermí"]
concatenada_Nombres_Apellidos= nombres + apellidos

print(concatenada_Nombres_Apellidos)

"""## Agregar elementos a una lista

Se puede agregar un elemento nuevo a una lista con el símbolo + y agregando el nuevo elemneto en [ ]
"""

lista2=[3, 4, 5, 6, 7, 8, 9, 10 ,11, 12]
#Agregar el número 13 sin volver a hacer la lista

lista2= lista2 + [13]
print(lista2)

# otra forma que se puede agregar un elemento a la lista con .append

lista2.append(13)
print(lista2)

# otra forma es con la función .insert a la cual se le puede dar la posición en la lista con .insert(posición, elemento)
lista2.insert(3, 13)
print(lista2)

#Si se desea imprimir varios elementos de la lista se puede usar el rango con [ : ]
lista2=[3, 4, 5, 6, 7, 8, 9, 10 ,11, 12]
print(lista2[0:6])

"""# Ciclo *for*

😞
"""

numbers=[1,2,3,4,5,6,7]

for a in numbers:
  print(a)

numbers=[1,2,3,4,5,6,7]

for a in numbers:
  print(a, end =" ")

nombres=["angela", "patricia", "isabella","carlos"]

for a in nombres:
  print(a, end =" ")

for a in nombres:
  print(a)

"""# Problemas en clase"""

lista1=["pedro", "2", "chamorro", "Colombia", "Tranquite" ,"Isbell" ,"Antonio" ,"Fernanda" ,"Alfredito","Jenny","Cristina"]
lista2=[3, 4, 5, 6, 7, 8, 9, 10 ,11, 12]
lista3=["Cartagena", "Barranquilla", "Santa Marta", "Malambo" ,"Aracataca" ,"Coveñas" ,"Sincelejo" ,"Ponedera", "Mompox", "Soledá","Mamatoco"]
print(lista1[0], lista1[4], lista1[9])
print(lista2[0], lista2[4], lista2[9])
print(lista3[0], lista3[4], lista3[9])

print("El tamaño de la lista es:", len(lista1))
print("El tamaño de la lista es:",len(lista2))
print("El tamaño de la lista es:",len(lista3))

"""Tengo una lista y la van a llenar de números y luego imprimen los números pares de la lista. 😟"""

numerosList=[1,2,56,78,45,34,22,44]

for i in numerosList:
  if i % 2 == 0:
    print(i)
  else:
    print("Fin")