# -*- coding: utf-8 -*-
"""20220518.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/ChrisBermudezR/6f4f8b38c8fa1a7ebe660264e72d5679/20220518.ipynb

# Manejo de archivos
"""

from io import open
archivo1= open("MiArchivo.txt", "w")
texto = "Luisa María\nIngeniera de Sistemas"
archivo1.write(texto)
archivo1.close()

"""**Ejercicio**

Cree un archivo de texto con los siguieentes datos
* Nombre
* Apellido
* Peso
* Estratura
* Fecha Nacimiento
* Empresa donde trabaja
* Ciudad 
* Dpto
* Pais
"""

from io import open
archivo1= open("MisDatos.txt", "w")
texto = "Nombre: Christian\nApellido: Bermúdez Rivas\nPeso:75 kg \nEstratura:1.70 \nFecha Nacimiento:19 enero 1980 \nEmpresa donde trabaja:Dirección General Marítima \nCiudad:Tumaco \nDpto:Nariño \nPais: Colombia"
archivo1.write(texto)
archivo1.close()

"""Para abrir un archivo:"""

#programa que abre el archivo en modo lectura; lea su contenido y lo ponga en pantalla
from io import open
NombreArchivo ="MisDatos.txt"
archivo1 =open(NombreArchivo,"r")
texto =archivo1.read()
archivo1.close()
print("ARCHIVO:",NombreArchivo)
print("Contenido:")
print(texto)

"""Programa para abrir archivo en modo lectura de lineas
.realines()
"""

#programa que abre el archivo en modo lectura; lea su contenido y lo ponga en pantalla como una lista
from io import open
NombreArchivo ="MisDatos.txt"
archivo1 =open(NombreArchivo,"r")
texto =archivo1.readlines()
archivo1.close()
print("ARCHIVO:",NombreArchivo)
print("Contenido:")
print(texto)

#programa que abre el archivo en modo lectura; lea su contenido y lo ponga en pantalla desde la posición de una lista
from io import open
NombreArchivo ="MisDatos.txt"
archivo1 =open(NombreArchivo,"r")
texto =archivo1.readlines()
archivo1.close()
print("ARCHIVO:",NombreArchivo)
print("Contenido:")
print(texto)
print(texto[3])

"""Manejo de archivos Binarios

Escribir un archivo binario
"""

import pickle #Librería para archivos binarios
datos=["Luisa María","Jimenez","36","1.56"]
archivo =open("Miarchivo.dat","wb")
pickle.dump(datos,archivo) #Función dump permite guardar datos archivos binarios
archivo.close()

"""Leer un archivo binario"""

#ARCIVOS BINARIOS//VER EL CONTENIDO
import pickle
archivo2 =open("Miarchivo.dat","rb")
datos = pickle.load (archivo2)
archivo2.close()

for c in datos:
  print(c)

"""Archivos JSON (JavaScriptObjectNotation)"""

#ARCHIVO JSON JSON (JavaScriptObjectNotation)
# Es un estandar utilizado para el intercambio de informacion entre aplicaciones. 
#Un objeto JSON es un diccionario donde la clave una cadena de caracteres delimitado por ""
# el valor puede se un numero, una cadena de caracteres, un elemento null,o una lista de elementos o un Json
{
"Nombre": "Douglas", 
"Apellido": "Crockford",
"pasatiempos": ["trotar","bucear","cantar"],
"edad": 64,
"empleado": false,
"jefe": null,
"hijos": [
    {"Nombre": "Alice","edad":16},
    {"Nombre": "Bob","edad":8}
  ]
}

import json
strjson=input()
s=input()
sl=s.split()
d=json.loads(strjson)
#Entrada: {"t": 66, "u": 72, "d": 90, "r": 84, "j": 36, "g": 50, "s": 94, "q": 62, "f": 35}
#Segunda Entrada: d p h u i e t q
print(d)