# -*- coding: utf-8 -*-
"""20220427.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kkt7hxNYx9JDUd9-edjQwpyRkZfMInyp

20220427

Ejercicios
1.	Haga un programa que calcule el porcentaje de alumnos perdidos y de alumnos que ganaron.
"""

#Ejercicio 1

def resultadosGrupo(total, ganadores):
  perdedores= total-ganadores
  porcentaje_ganadores=ganadores*100/total
  porcentaje_perdedores=100-porcentaje_ganadores
  return print(f'El porcentaje de los estudiantes que ganaron el año fue del {porcentaje_ganadores}% y El porcentaje de los estudiantes que perdieron el año fue del {porcentaje_perdedores}%')

total=(int(input("¿Cuál es el total de estudiantes en el grupo? ")))
ganadores=(int(input("¿Cuantos estudiantes ganaron el año? ")))

resultadosGrupo(total, ganadores)

"""2.	Haga un programa que calcule el valor de un computador si es día de descuento.

"""

#Ejercicio 2

def f(precio, descuento):
   return precio-(precio*descuento/100)

precio=(float(input("Precio ")))
descuento=(float(input("Descuento ")))

f(precio, descuento)

"""3.	Haga un programa que calcule el salario básico para un empleado sabiendo que el empleado gana un salario bruto, a ese salario bruto se le descuenta el 10% por la retención en la fuente, 1% para Sena, 1% para icbf y 2% por estampilla. Y sobre el valor resultante se le descuenta el 0.4%  correspondiente al 4*1000."""

#Ejercicio 3

def f(SalarioBruto,y):
  salarioFinal = SalarioBruto-()

"""4.	Haga un programa que dados dos numero diga cuál es el mayor"""

#Ejercicio 4

def f(x,y): 
  if x > y :
    return print(f"{x} es mayor que {y}")
  elif y > x:
    return print(f'{y} es mayor que {x}')
  elif y== x:
    return print(f'{y} y {x} son iguales')
x=(float(input("digite un número: ")))
y=(float(input("digite otro número: ")))
f(x,y)

"""5.	Haga un programa que calcule el promedio de notas para 3 notas.  Si el promedio es menor a 3 aparezca un mensaje el estudiante perdió en caso contrario diga el estudiante gano."""

#Ejercicio 5

import statistics
def f(x,y,z):
  notas=[x,y,z]
  promedio = sum(notas) /  len(notas)
  if promedio < 3:
    return print("El estudiante perdió la materia")
  else:
    return print("El estudiante ganó la materia")
x=float(input("Nota 1: "))
y=float(input("Nota 2: "))
z=float(input("Nota 3: "))

f(x,y,z)

"""6.	Haga un programa que calcule el promedio de notas para 3 notas.  Si el promedio es menor a tres aparezca un mensaje el estudiante perdió, si el promedio es mayor o igual a tres y menor que cuatro aparezca  un mensaje bien es estudiante gano, si el promedio es mayor o igual a cuatro el mensaje diga excelente promedio superior. """

#Ejercicio 5

import statistics
def f(x,y,z):
  notas=[x,y,z]
  promedio = sum(notas) /  len(notas)
  if promedio < 3:
    return print(f'El estudiante perdió la materia. Su promedio es {promedio}')
  elif promedio >= 3 and promedio < 4:
    return print(f'El estudiante ganó la materia. Su promedio es {promedio}')
  elif promedio > 4:
    return print(f'El estudiante es excelente. Su promedio es {promedio}')
x=float(input("Nota 1: "))
y=float(input("Nota 2: "))
z=float(input("Nota 3: "))
f(x,y,z)

"""7.	Haga un programa que dado un número, si este es mayor que 30 calcule el cubo, en caso contrario calcule el cuadrado."""

def f(x):
  if x >30:
    return x**3
  else:
    return x**2
x=float(input('Ingrese un número: '))
f(x)

"""8.	Haga un programa que calcule el salario neto de un empleado sabiendo que el salario básico de él se calcula de acuerdo a número de horas trabajadas y la hora tiene un valor especifico, además si ese salario es menor que dos salarios mínimos legales vigente (smlv) se le paga un subsidio de transporte equivalente a 55000.  (el smlv=565000)."""

def f(basico, horas):
  if