# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ChrisBermudezR/Mintic_2022/blob/main/Problemas_Pesos.ipynb
"""

#Problema 2022-04-25
print("En vereda encantada  Gi, Ale y Nico  quieren saber cuanto pesan y utilizan la bascula del abuelo. Al quitarle cuatro kilos al peso de Gi se obtiene dos veces el peso de Ale y si sumamos los pesos de Gi y Ale se obtiene cinco veces el peso de Nico (todos los pesos son enteros).") 
Gio=int(input("Cuanto es el peso de Gio:"))
Ale=(Gio-4)/2
Nico= (Ale+Gio)/5
print(f"El peso de Gio es: {Gio}")
print(f"El peso de Gio es: {Ale}")
print(f"El peso de Gio es: {Nico}")

"""Funciones para cácular el área del circulo"""

def f(x):
  return 3.1416*x**2
  f(23)
print(f(23))

"""Cálculo de valores"""

def f(x):
  a = x**2
  b= x**3
  c = x*x
  d = x*x*x
  return print(a,b,c,d)
f(3)

"""Interés compuesto"""

def f(x):
  cf = x*(1 + 0.13)**15
  return print(cf)
f(95000000)

"""Reto de la primera semana!"""

if __name__ == '__main__':
	hijo = float()
	padre = int()
	madre = int()
	print("Cu�l es el peso del padre en kg: ")
	padre = int(input())
	madre = 2*padre+4
	hijo = (madre+padre)/5
	print(padre)
	print(madre)
	print(int(hijo))
	if hijo>=0 and hijo<=20:
		print("uno")
	else:
		if hijo>=21 and hijo<=40:
			print("dos")
		else:
			if hijo>=41 and hijo<=80:
				print("tres")
			else:
				if hijo>80:
					print("cuatro")